B_Sourcecode/tech-in-vein/models/Comment.php
<?php

namespace app\models;

use Yii;
use Yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\base\NotSupportedException;
use dektrium\user\models\User;

class Comment extends ActiveRecord
{
    // Get table name
	public static function getTableName()
	{
		return '{{%comment}}';
	}

	public function rules()
	{
		return [
            [['post_id', 'user_id', 'content'], 'required'],
			['content', 'string', 'max' => 1024]
		];
	}

	public function behaviors()
	{
		return [
			'timestamp' => [
				'class' => TimestampBehavior::className(),
				'attributes' => [
					ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
					ActiveRecord::EVENT_BEFORE_UPDATE => 'updated_at',
					ActiveRecord::EVENT_BEFORE_DELETE => 'updated_at',
				],
			],
		];
	}

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function create()
    {
        if ($this->getIsNewRecord() == false)
        {
            throw new \RuntimeException('Calling "' . __CLASS__ . '::' . __METHOD__ . '" on existing tag');
        }
        return $this->save();
    }
}

B_Sourcecode/tech-in-vein/controllers/PostController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Post;
use app\models\Comment;
use app\models\PostEditForm;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\AccessControl;
use yii\helpers\Url;

/**
* All actions of Post
*/
class PostController extends Controller
{
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					['allow' => true, 'actions' => ['create', 'manage', 'publish', 'delete', 'edit', 'comment'], 'roles' => ['@']],
					['allow' => true, 'actions' => ['view', 'tag'], 'roles' => ['?', '@']],
				],
			],
			'verbs' => [
	            'class' => \yii\filters\VerbFilter::className(),
	            'actions' => [
	                'fbauthorize'  => ['post'],
	            ],
	        ]
		];
	}

	public function actionView()
	{
		if (!Yii::$app->request->getIsGet())
		{
			return $this->render('/site/error', [
				'name' => 'Invalid request action',
				'message' => 'Your request action cannot be processed!'
			]);
		}
		$postId = Yii::$app->request->getQueryParam('id');
		if (empty($postId))
		{
			return $this->render('/site/error', [
				'name' => 'Invalid request action',
				'message' => 'Your request action cannot be processed!'
			]);
		}
		$model = Post::findOne($postId);
		if (empty($model) || ($model->status != Post::STATUS_PUBLISH && $model->user->id != Yii::$app->user->id))
		{
			return $this->render('/site/error', [
				'name' => 'Information not found',
				'message' => 'Post information cannot found!',
			]);
		}
		$model->content = $this->setCodeTag($model);
		return $this->render('/site/post/view', [
			'model' => $model,
			'profile' => $model->user->profile,
			'relatedPosts' => $model->getRelatedPosts($model->user->id, $postId, $model->type),
		]);
	}

	public function actionCreate()
	{
		// create new post form
		$model = new PostEditForm(['scenario' => PostEditForm::SCENARIO_CREATE]);

		if (Yii::$app->request->isPost)
		{
			$model->attributes = Yii::$app->request->post('PostEditForm');
			if ($model->create())
			{
				$viewUrl = Url::to(['/post/view', 'id' => $model->getPostId()]);
				return $this->redirect($viewUrl);
			}
		}

		$model->type = Post::TYPE_ARTICLE; // article
		$model->status = Post::STATUS_PUBLISH; // publish post
		return $this->render('/site/post/edit', [
			'model' => $model
		]);
	}

	public function actionEdit()
	{
		$model = new PostEditForm(['scenario' => PostEditForm::SCENARIO_EDIT]);

		if (Yii::$app->request->isGet)
		{
			$postId = Yii::$app->request->getQueryParam('id');
			$post = Post::findOne($postId);
			if (isset($post) &&
				$post->user_id == Yii::$app->user->id &&
				($post->status == Post::STATUS_PUBLISH || $post->status == Post::STATUS_DRAFT))
			{
				$model->loadAttributesFromPost($post);
				return $this->render('/site/post/edit', [
					'model' => $model
				]);
			}
		}

		if (Yii::$app->request->isPut)
		{
			$model->attributes = Yii::$app->request->post('PostEditForm');
			if ($model->edit())
			{
				$viewUrl = Url::to(['/post/view', 'id' => $model->getPostId()]);
				return $this->redirect($viewUrl);
			}
			return $this->render('/site/post/edit', [
				'model' => $model
			]);
		}

		return $this->render('/site/error', [
			'name' => 'Information not found',
			'message' => 'Post information cannot found!',
		]);
	}

	public function actionManage()
	{
		$allPostsByUser = Post::getAllPostsByUser(Yii::$app->user->id);
		return $this->render('/site/post/manage', [
			'posts' => $allPostsByUser
		]);
	}

	public function actionPublish()
	{
		if (!Yii::$app->request->isAjax || !Yii::$app->request->isPut) return false;
		// use getRawBody() or file_get_contents("php://input")
		$rawData = Yii::$app->request->getRawBody();
		$requestData = (Array)json_decode($rawData);
		$postId = $requestData['post_id'];
		if (!isset($postId)) return false;
		$post = Post::findOne($postId);
		if (!isset($post) || $post->status == Post::STATUS_PUBLISH) return false;
		return $post->edit(array('status' => Post::STATUS_PUBLISH));
	}

	public function actionDelete()
	{
		if (!Yii::$app->request->isAjax || !Yii::$app->request->isDelete) return false;
		$rawData = Yii::$app->request->getRawBody();
		$requestData = (Array)json_decode($rawData);
		$postId = $requestData['post_id'];
		if (!isset($postId)) return false;
		$post = Post::findOne($postId);
		if (!isset($post) || $post->status == Post::STATUS_DELETE) return false;
		return $post->edit(array('status' => Post::STATUS_DELETE));
	}

	public function actionTag()
	{
		if (!Yii::$app->request->isGet)
		{
			return $this->render('/site/error', [
				'name' => 'Invalid request action',
				'message' => 'Your request action cannot be processed!'
			]);
		}
		$tagName = Yii::$app->request->getQueryParam('name');
		$postsByTag = Post::getPostsByTag($tagName);
		return $this->render('/site/post/tag', [
			'postsByTag' => $postsByTag
		]);
	}

	public function actionComment()
	{
		if (!Yii::$app->request->isAjax || !Yii::$app->request->isPost) return false;
		$rawData = Yii::$app->request->getRawBody();
		$requestData = (Array)json_decode($rawData);
		$postId = $requestData['post_id'];
		$comment = $requestData['comment'];
		if (!isset($postId) || !isset($comment)) return false;
		$commentData = Yii::createObject(Comment::className());
		$commentData->post_id = $postId;
		$commentData->user_id = Yii::$app->user->id;
		$commentData->content = $comment;
		if ($commentData->create())
		{
			\Yii::$app->response->format = 'json';
			return $this->commentAttributes($commentData);
		}
		return false;
	}

	// Replace origin <pre> tag for custom Prism code tag
	private function setCodeTag(Post $post)
	{
		$postContent = $post->content;
		if (!empty($postContent))
		{
			if (strpos($postContent,'<pre>') && strpos($postContent,'</pre>'))
			{
				$postContent = str_ireplace('<pre>', '<pre><code class="language-c">', $postContent);
				$postContent = str_ireplace('</pre>', '</code></pre>', $postContent);
			}
		}
		return $postContent;
	}

	private function commentAttributes(Comment $comment)
	{
		return [
			'id'  		 => $comment->id,
			'post_id'    => $comment->post_id,
			'user_id'    => $comment->user_id,
			'comment'    => $comment->content,
			'point'      => $comment->point,
			'created_at' => $comment->created_at,
			'updated_at' => $comment->updated_at
		];
	}
}

B_Sourcecode/tech-in-vein/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\ContactForm;

use app\models\Post;
use app\models\Tag;
use app\models\EmailSubscribe;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        if (!Yii::$app->request->getIsGet())
        {
            return $this->render('/site/error', [
                'name' => 'Invalid request action',
                'message' => 'Your request action cannot be processed!'
            ]);
        }

        $postType = Yii::$app->request->get('type');
        $allPosts = Post::find()->with('comments')->where([
            'status'     => Post::STATUS_PUBLISH,
            'view_scope' => Post::SCOPE_PUBLIC,
            'type'       => (isset($postType) && ($postType == Post::TYPE_ARTICLE || $postType == Post::TYPE_QUESTION)) ? (int) $postType : Post::TYPE_ARTICLE
        ])->orderBy('updated_at DESC')->all();

        return $this->render('index', [
            'posts' => $allPosts,
            'latestPosts' => Post::getLatestPost(),
            'topTags' => Tag::getTopTags()
        ]);
    }

    public function actionSearch()
    {
        if (!Yii::$app->request->isGet) return false;
        $searchText = Yii::$app->request->get('search_text');
        if (isset($searchText)) {
            return $this->render('/site/search', [
                'posts' => [],
            ]);
        }
        $searchPosts = Post::find()->with('comments')->where(
            'status = ' . Post::STATUS_PUBLISH . ' and view_scope = ' . Post::SCOPE_PUBLIC . ' and (title like "%' . $searchText . '%" or content like "%' . $searchText . '%" or tags like "%' . $searchText . '%")'
        )->orderBy('updated_at DESC')->all();

        return $this->render('/site/search', [
            'posts' => $searchPosts,
        ]);
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionSubscribe()
    {
        if (!Yii::$app->request->isAjax || !Yii::$app->request->isPost) return false;
        $rawData = Yii::$app->request->getRawBody();
		$requestData = (Array)json_decode($rawData);
		$emailAddress = $requestData['email'];
        if (!isset($emailAddress)) return false;
        if (!filter_var($emailAddress, FILTER_VALIDATE_EMAIL)) return false;
        $subscribe = Yii::createObject(EmailSubscribe::className());
        $subscribe->email = $emailAddress;
        $subscribe->active = 1;
        return $subscribe->subscribe();
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

B_Sourcecode/tech-in-vein/views/site/comment/_edit.php
<?php

use yii\helpers\Html;
use app\models\Comment;

$onCommentViewJs = <<< 'SCRIPT'

$(function () {
    $("#post-comment-edit-textarea").redactor({
        changeCallback: function() { },
    });

    $("#post-comment-reset-button").click(function() {
        $("#modal-title-label").text('Reset form');
        $("#modal-body-label").text('Are you sure want to clear all information in this form?');
        $("#modal-confirm-button").click(function() {
            $("#post-comment-edit-textarea").redactor('code.set', '');
            $("#modal-confirm-dialog").modal('hide');
        });
        $("#modal-confirm-dialog").modal('toggle');
    });

    $("#post-comment-reply-button").click(function() {
        $("#modal-title-label").text('Send Comment');
        $("#modal-body-label").text('Are you sure want to send this comment?');
        $("#modal-confirm-button").click(function() {
            $.ajax({
                type: "POST",
                url: '/post/comment',
                dataType: 'json',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({post_id: getParameterByName('id'), comment: document.getElementById("post-comment-edit-textarea").value}),
                success: function(data) {
                    location.reload();
                },
                error: function(xhr, textStatus, errorThrown) {
                    alert("Something wrong! You cannot post a comment. Please try again.");
                }
            });
            $("#modal-confirm-dialog").modal('hide');
        });
        $("#modal-confirm-dialog").modal('toggle');
    });
});

SCRIPT;
$this->registerJs($onCommentViewJs);

?>

<?php if (Yii::$app->user->isGuest): ?>
    <h4 class="well" style="width: 100%; margin: 0 auto; text-align: center;">
        Sign in as member to comment.
    </h4>
<?php else: ?>
    <form class="form-horizontal">
        <fieldset>
            <legend>Comment</legend>
            <div>
                <textarea id="post-comment-edit-textarea" placeholder="Comment..." name="content" rows="5" maxlength="50"></textarea>
            </div>
        </fieldset>
    </form>
    <ul class="pull-right list-inline">
        <button id="post-comment-reply-button" class="btn btn-primary" style="margin-right: 10px;">Reply</button>
        <button id="post-comment-reset-button" class="btn btn-default">Reset</button>
    </ul>
<?php endif; ?>
<br />
<br />
<hr>
<?php if (isset($comments) && count($comments)): ?>
    <table class="table table-striped table-hover "><tbody>
        <?php foreach ($comments as $comment): ?>
            <tr>
                <div class="row">
                    <div class="col-md-2" style="margin: 10px 0 10px 0;">
                        <a href="/user/profile?id=<?= $comment->user->id ?>" style="align-text: center;">
                            <img src="http://gravatar.com/avatar/<?= $comment->user->profile->gravatar_id ?>?s=230" class="img-circle pull-left" style="width: 60px; height: 60px;" />
                        </a>
                    </div>
                    <div class="col-md-10">
                        <div><a href="/user/profile?id=<?= $comment->user->id ?>" style="align-text: center;">
                            <h5 style="margin-left: -15px; padding-left: 0px; font-weight: bold;"><?php echo $comment->user->username; ?></h5>
                        </a></div>
                        <div><p style="margin-left: -15px; padding-left: 0px;"><?= Html::encode(date('F jS, Y | h:i:s A', $comment->created_at)); ?></p></div>
                    </div>
                </div>
                <div class="row">
                    <div class="well well-sm col-md-11" style="margin: 0 -10px 0 10px; word-wrap: break-word;">
                        <p class="post-content-text" style="margin-left: -20px; padding-left: 0px; font-size: 14pt;"><?= $comment->content; ?></p>
                    </div>
                </div>
                <hr>
            </tr>
        <?php endforeach; ?>
    </tbody></table>
<?php else: ?>
    <h4 class="well" style="width: 100%; margin: 0 auto; text-align: center;">
        No comments
    </h4>
<?php endif; ?>