B_Sourcecode/tech-in-vein/controllers/ImageController.php
<?php

namespace app\controllers;

use Yii;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\AccessControl;

/**
* All actions of Image Upload & Process
*/
class ImageController extends Controller
{
    public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					['allow' => true, 'actions' => ['upload', 'delete'], 'roles' => ['@']],
				],
			],
			'verbs' => [
	            'class' => \yii\filters\VerbFilter::className(),
	            'actions' => [
	                'fbauthorize'  => ['post'],
	            ],
	        ]
		];
	}

    public function actionUpload()
    {
        if (!Yii::$app->request->isAjax || !Yii::$app->request->isPost) return false;
        if (isset($_GET['files'])) return false;
        $file = $_FILES[0];
        $fileName = $file['tmp_name'];
        $fileHandle = fopen($fileName, "r");
        $data = fread($fileHandle, filesize($fileName));
        $requestData = array('image' => base64_encode($data), 'title' => $file['name']);
        $timeout = 30;
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, 'https://api.imgur.com/3/image.json');
        curl_setopt($curl, CURLOPT_TIMEOUT, $timeout);
        curl_setopt($curl, CURLOPT_HTTPHEADER, array('Authorization: Client-ID ' . \Yii::$app->params['imgurClientID']));
        curl_setopt($curl, CURLOPT_POST, 1);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $requestData);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
        $out = curl_exec($curl);
        curl_close($curl);
        $pms = json_decode($out,true);
        $url = $pms['data']['link'];
        \Yii::$app->response->format = 'json';
        if($url != ""){
            return ['imageId' => $pms['data']['id'], 'imageUrl' => $url, 'deletehash' => $pms['data']['deletehash']];
        }else{
            return ['error' => $pms['data']['error']];
        }
    }

    public function actionDelete()
    {
        if (!Yii::$app->request->isAjax || !Yii::$app->request->isDelete) return false;
        $rawData = Yii::$app->request->getRawBody();
		$requestData = (Array)json_decode($rawData);
		$imageDeleteHash = $requestData['delete_hash'];
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, 'https://api.imgur.com/3/image/' . $imageDeleteHash);
        curl_setopt($curl, CURLOPT_TIMEOUT, 30);
        curl_setopt($curl, CURLOPT_HTTPHEADER, array('Authorization: Client-ID ' . \Yii::$app->params['imgurClientID']));
        curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'DELETE');
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
        $out = curl_exec($curl);
        curl_close($curl);
        $pms = json_decode($out,true);
        \Yii::$app->response->format = 'json';
        return ['success' => $pms['success'], 'status' => $pms['status']];
    }
}

B_Sourcecode/tech-in-vein/controllers/PostController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Post;
use app\models\Comment;
use app\models\PostEditForm;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\AccessControl;
use yii\helpers\Url;

/**
* All actions of Post
*/
class PostController extends Controller
{
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					['allow' => true, 'actions' => ['create', 'manage', 'publish', 'delete', 'edit', 'comment'], 'roles' => ['@']],
					['allow' => true, 'actions' => ['view', 'tag'], 'roles' => ['?', '@']],
				],
			],
			'verbs' => [
	            'class' => \yii\filters\VerbFilter::className(),
	            'actions' => [
	                'fbauthorize'  => ['post'],
	            ],
	        ]
		];
	}

	public function actionView()
	{
		if (!Yii::$app->request->getIsGet())
		{
			return $this->render('/site/error', [
				'name' => 'Invalid request action',
				'message' => 'Your request action cannot be processed!'
			]);
		}
		$postId = Yii::$app->request->getQueryParam('id');
		if (empty($postId))
		{
			return $this->render('/site/error', [
				'name' => 'Invalid request action',
				'message' => 'Your request action cannot be processed!'
			]);
		}
		$model = Post::findOne($postId);
		if (empty($model) || ($model->status != Post::STATUS_PUBLISH && $model->user->id != Yii::$app->user->id))
		{
			return $this->render('/site/error', [
				'name' => 'Information not found',
				'message' => 'Post information cannot found!',
			]);
		}
		$model->content = $this->setCodeTag($model);
		return $this->render('/site/post/view', [
			'model' => $model,
			'profile' => $model->user->profile,
			'relatedPosts' => $model->getRelatedPosts($model->user->id, $postId, $model->type),
		]);
	}

	public function actionCreate()
	{
		// create new post form
		$model = new PostEditForm(['scenario' => PostEditForm::SCENARIO_CREATE]);

		if (Yii::$app->request->isPost)
		{
			$model->attributes = Yii::$app->request->post('PostEditForm');
			if ($model->create())
			{
				$viewUrl = Url::to(['/post/view', 'id' => $model->getPostId()]);
				return $this->redirect($viewUrl);
			}
		}

		$model->type = Post::TYPE_ARTICLE; // article
		$model->status = Post::STATUS_PUBLISH; // publish post
		return $this->render('/site/post/edit', [
			'model' => $model
		]);
	}

	public function actionEdit()
	{
		$model = new PostEditForm(['scenario' => PostEditForm::SCENARIO_EDIT]);

		if (Yii::$app->request->isGet)
		{
			$postId = Yii::$app->request->getQueryParam('id');
			$post = Post::findOne($postId);
			if (isset($post) &&
				$post->user_id == Yii::$app->user->id &&
				($post->status == Post::STATUS_PUBLISH || $post->status == Post::STATUS_DRAFT))
			{
				$model->loadAttributesFromPost($post);
				return $this->render('/site/post/edit', [
					'model' => $model
				]);
			}
		}

		if (Yii::$app->request->isPut)
		{
			$model->attributes = Yii::$app->request->post('PostEditForm');
			if ($model->edit())
			{
				$viewUrl = Url::to(['/post/view', 'id' => $model->getPostId()]);
				return $this->redirect($viewUrl);
			}
			return $this->render('/site/post/edit', [
				'model' => $model
			]);
		}

		return $this->render('/site/error', [
			'name' => 'Information not found',
			'message' => 'Post information cannot found!',
		]);
	}

	public function actionManage()
	{
		$allPostsByUser = Post::getAllPostsByUser(Yii::$app->user->id);
		return $this->render('/site/post/manage', [
			'posts' => $allPostsByUser
		]);
	}

	public function actionPublish()
	{
		if (!Yii::$app->request->isAjax || !Yii::$app->request->isPut) return false;
		// use getRawBody() or file_get_contents("php://input")
		$rawData = Yii::$app->request->getRawBody();
		$requestData = (Array)json_decode($rawData);
		$postId = $requestData['post_id'];
		if (!isset($postId)) return false;
		$post = Post::findOne($postId);
		if (!isset($post) || $post->status == Post::STATUS_PUBLISH) return false;
		return $post->edit(array('status' => Post::STATUS_PUBLISH));
	}

	public function actionDelete()
	{
		if (!Yii::$app->request->isAjax || !Yii::$app->request->isDelete) return false;
		$rawData = Yii::$app->request->getRawBody();
		$requestData = (Array)json_decode($rawData);
		$postId = $requestData['post_id'];
		if (!isset($postId)) return false;
		$post = Post::findOne($postId);
		if (!isset($post) || $post->status == Post::STATUS_DELETE) return false;
		return $post->edit(array('status' => Post::STATUS_DELETE));
	}

	public function actionTag()
	{
		if (!Yii::$app->request->isGet)
		{
			return $this->render('/site/error', [
				'name' => 'Invalid request action',
				'message' => 'Your request action cannot be processed!'
			]);
		}
		$tagName = Yii::$app->request->getQueryParam('name');
		$postsByTag = Post::getPostsByTag($tagName);
		return $this->render('/site/post/tag', [
			'postsByTag' => $postsByTag
		]);
	}

	public function actionComment()
	{
		if (!Yii::$app->request->isAjax || !Yii::$app->request->isPost) return false;
		$rawData = Yii::$app->request->getRawBody();
		$requestData = (Array)json_decode($rawData);
		$postId = $requestData['post_id'];
		$comment = $requestData['comment'];
		if (!isset($postId) || !isset($comment)) return false;
		$commentData = Yii::createObject(Comment::className());
		$commentData->post_id = $postId;
		$commentData->user_id = Yii::$app->user->id;
		$commentData->content = $comment;
		if ($commentData->create())
		{
			\Yii::$app->response->format = 'json';
			return $this->commentAttributes($commentData);
		}
		return false;
	}

	// Replace origin <pre> tag for custom Prism code tag
	private function setCodeTag(Post $post)
	{
		$postContent = $post->content;
		if (!empty($postContent))
		{
			if (strpos($postContent,'<pre>') && strpos($postContent,'</pre>'))
			{
				$postContent = str_ireplace('<pre>', '<pre><code class="language-c">', $postContent);
				$postContent = str_ireplace('</pre>', '</code></pre>', $postContent);
			}
		}
		return $postContent;
	}

	private function commentAttributes(Comment $comment)
	{
		return [
			'id'  		 => $comment->id,
			'post_id'    => $comment->post_id,
			'user_id'    => $comment->user_id,
			'comment'    => $comment->content,
			'point'      => $comment->point,
			'created_at' => $comment->created_at,
			'updated_at' => $comment->updated_at
		];
	}
}

B_Sourcecode/tech-in-vein/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\ContactForm;

use app\models\Post;
use app\models\Tag;
use app\models\EmailSubscribe;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        if (!Yii::$app->request->getIsGet())
        {
            return $this->render('/site/error', [
                'name' => 'Invalid request action',
                'message' => 'Your request action cannot be processed!'
            ]);
        }

        $postType = Yii::$app->request->get('type');
        $allPosts = Post::find()->with('comments')->where([
            'status'     => Post::STATUS_PUBLISH,
            'view_scope' => Post::SCOPE_PUBLIC,
            'type'       => (isset($postType) && ($postType == Post::TYPE_ARTICLE || $postType == Post::TYPE_QUESTION)) ? (int) $postType : Post::TYPE_ARTICLE
        ])->orderBy('updated_at DESC')->all();

        return $this->render('index', [
            'posts' => $allPosts,
            'latestPosts' => Post::getLatestPost(),
            'topTags' => Tag::getTopTags()
        ]);
    }

    public function actionSearch()
    {
        if (!Yii::$app->request->isGet) return false;
        $searchText = Yii::$app->request->get('search_text');
        if (isset($searchText)) {
            return $this->render('/site/search', [
                'posts' => [],
            ]);
        }
        $searchPosts = Post::find()->with('comments')->where(
            'status = ' . Post::STATUS_PUBLISH . ' and view_scope = ' . Post::SCOPE_PUBLIC . ' and (title like "%' . $searchText . '%" or content like "%' . $searchText . '%" or tags like "%' . $searchText . '%")'
        )->orderBy('updated_at DESC')->all();

        return $this->render('/site/search', [
            'posts' => $searchPosts,
        ]);
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionSubscribe()
    {
        if (!Yii::$app->request->isAjax || !Yii::$app->request->isPost) return false;
        $rawData = Yii::$app->request->getRawBody();
		$requestData = (Array)json_decode($rawData);
		$emailAddress = $requestData['email'];
        if (!isset($emailAddress)) return false;
        if (!filter_var($emailAddress, FILTER_VALIDATE_EMAIL)) return false;
        $subscribe = Yii::createObject(EmailSubscribe::className());
        $subscribe->email = $emailAddress;
        $subscribe->active = 1;
        return $subscribe->subscribe();
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

B_Sourcecode/tech-in-vein/views/site/post/_item.php
<?php

use app\models\Post;
use yii\helpers\Html;

$postDetailUrl = '/post/view?id=' . $post->id;

?>

<div class='panel panel-default'>
	<div class='panel-body' style="padding-left: 3%; padding-right: 3%;">
		<?php if (!empty($post) && $post->type == Post::TYPE_QUESTION): ?>
			<div>
				<p class="label label-warning">Need help</p>
			</div>
		<?php endif; ?>
		<a href="<?= $postDetailUrl ?>" style="font-weight: bold; font-size: 24pt; color: #444444; text-decoration: none; word-wrap: break-word; width: auto;">
			<?php if (!empty($post)) echo $post->title; ?>
		</a>
		<br/>
		<a href="/user/profile?id=<?= $post->user->id ?>"><?= $post->user->username ?></a> ・
		<?= Html::encode(date('F jS, Y', $post->updated_at)); ?> ・
		<a href="<?= $postDetailUrl ?>"><?= count($post->comments) . " comments" ?></a>
		<?php if (!empty($post->getTags()) && count($post->getTags()) > 0): ?>
			<div>
	            <?php foreach ($post->getTags() as $tag): ?>
	                <a href="/post/tag?name=<?= $tag; ?>" class="label label-info"><?php echo $tag; ?></a>
	            <?php endforeach; ?>
			</div>
			<br/>
		<?php else: ?>
			<br/>
			<br/>
		<?php endif; ?>
		<a href="<?= $postDetailUrl ?>" style="line-height: 30px; color: #4A4A4A; text-decoration: none; font-size: 12pt; word-wrap: break-word;">
			<?php
				if (isset($post))
				{
					if (strlen($post->content) <= 256)
					{
						echo $post->content;
					}
					else
					{
						$originContentString = strip_tags($post->content, '<pre>');
						$originContentString = substr($originContentString, 0, 255);
						while (substr_count($originContentString, '<p>') > 5)
						{
							$originContentString = substr($originContentString, 0, strlen($originContentString) - 2);
						}
						echo $originContentString . "...";
					}
				}
			?>
		</a>
		<br/>
		<a href="<?= $postDetailUrl ?>" class="text-primary" style="text-decoration: none;">Read more</a>
	</div>
</div>

B_Sourcecode/tech-in-vein/views/site/post/edit.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\bootstrap\Tabs;

$this->title = (isset($mode) && $mode == 'create') ? "Create new post" : "Edit post";

$onEditJs = <<< 'SCRIPT'

$(function () {
    // Post content edit tips
    $("[data-toggle='tooltip']").tooltip();

    // Init content ckeditor & update text into Content preview
    $("#edit-content-textbox").redactor({
        changeCallback: function()
        {
            // code here
        }
    });

    // Form Reset button click event
    $("#post-reset-button").click(function() {
        $("#modal-title-label").text('Reset form');
        $("#modal-body-label").text('Are you sure want to clear all information in this form?');
        $("#modal-confirm-button").click(function() {
            $("#edit-title-textbox").val("");
            $("#edit-content-textbox").redactor('code.set', '');
            $("#edit-tag-textbox").val("");
            $("#edit-scope-dropdownlist").val("0");
            $('input[id="edit-type-selection"]').val([0]);
            $("#edit-comment-dropdownlist").val("0");
            $("#modal-confirm-dialog").modal('hide');
        });
        $("#modal-confirm-dialog").modal('toggle');
    });

    // Preview tab selected event
    $('a[href="#w0-tab1"]').on('shown.bs.tab', function (e) {
        var previewTitleLabel = document.getElementById("preview-title-label");
        var editTitleLabel = document.getElementById("edit-title-textbox");
        previewTitleLabel.innerHTML = editTitleLabel.value;

        var previewContentLabel = document.getElementById("preview-content-label");
        var editContentLabel = document.getElementById("edit-content-textbox");
        previewContentLabel.innerHTML = editContentLabel.value;
    });

    // Publish button click event
    $("#post-submit-button").click(function() {
        $("#modal-title-label").text('Publish this article');
        $("#modal-body-label").text('Are you sure want to publish this article right now?');
        $("#modal-confirm-button").click(function() {
            var statusHiddenValue = document.getElementById("edit-status-value");
            statusHiddenValue.value = "0";
            document.getElementById("post-create-form").submit();
        });
        $("#modal-confirm-dialog").modal('toggle');
    });

    // Save Draft button click event
    $("#post-draft-button").click(function() {
        $("#modal-title-label").text('Save article as a draft');
        $("#modal-body-label").text('Are you sure want to save this article as a draft?');
        $("#modal-confirm-button").click(function() {
            var statusHiddenValue = document.getElementById("edit-status-value");
            statusHiddenValue.value = "1";
            document.getElementById("post-create-form").submit();
        });
        $("#modal-confirm-dialog").modal('toggle');
    });


    $("#post-image-input-file").change(function() {
        var input = $(this), numFiles = input.get(0).files ? input.get(0).files.length : 1, label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
        input.trigger('fileselect', [numFiles, label]);

        var postImageUploadProgressBar = document.getElementById("post-image-upload-progress-bar");
        if (input.get(0).files.length > 0)
        {
            postImageUploadProgressBar.setAttribute("style", "");
            var imageData = new FormData();
            $.each(input.get(0).files, function(key, value) {
                imageData.append(key, value);
            });

            $.ajax({
                url: "/image/upload",
                type: "POST",
                data:  imageData,
                dataType: 'json',
                contentType: false,
                processData:false,
                cache: false,
                success: function(data) {
                    // success
                    postImageUploadProgressBar.setAttribute("style", "display: none;");
                    $("#edit-content-textbox").redactor('insert.html', '<br><p class="text-center"><img src="' + data.imageUrl + '" style="max-width:100%; max-height:100%;"></p><br>');
                },
                error: function(xhr, errorStatus, errorThrown){
                    // error
                    postImageUploadProgressBar.setAttribute("style", "display: none;");
                    alert("Something wrong! The image has not been uploaded yet! Please try again.");
                }
            });
        }
    });

    $('.btn-file :file').on('fileselect', function(event, numFiles, label) {
        var input = $(this).parents('.input-group').find(':text'),
            log = numFiles > 1 ? numFiles + ' files selected' : '  ' + label;
        if( input.length ) {
            input.val(log);
        } else {
            if( log ) alert(log);
        }
    });
});

SCRIPT;
$this->registerJs($onEditJs);

?>

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <?php

            echo Tabs::widget([
                'items' => [
                    [
                        'label' => 'Edit',
                        'content'=> $this->render('_edit', ['model' => $model]),
                        'active' => true,
                        'data-toggle' => 'edit',
                    ],
                    [
                        'label' => 'Preview',
                        'content' => $this->render('_preview', ['model' => $model]),
                        'data-toggle' => 'preview',
                    ],
                ],
                'options' => ['class' => 'nav nav-tabs nav-justified']
            ]);
        ?>

    </div>
</div>

B_Sourcecode/tech-in-vein/views/site/post/view.php
<?php

use yii\helpers\Html;
use app\models\Post;

if (!empty($model)) $this->title = $model->title;

$onPostDetailJS = <<< 'SCRIPT'

$(function() {
    $("#post-detail-publish-button").click(function() {
        $("#modal-title-label").text('Publish this article');
        $("#modal-body-label").text('Are you sure want to publish this article right now?');
        $("#modal-confirm-button").click(function() {
            $.ajax({
                type: "PUT",
                url: '/post/publish',
                dataType: 'json',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({post_id: getParameterByName("id")}),
                success: function(data) {
                    window.location.replace("/post/manage");
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    alert("Something wrong! Cannot publish this article. Please try again.");
                }
            });
            $("#modal-confirm-dialog").modal('hide');
        });
        $("#modal-confirm-dialog").modal('toggle');
    });

    $("#post-detail-edit-button").click(function() {
        var postId = document.getElementById("post-id").value;
        window.location.replace("/post/edit?id=" + postId);
    });

    $("#post-detail-delete-button").click(function() {
        $("#modal-title-label").text('Delete this article');
        $("#modal-body-label").text('Are you sure want to delete this article?');
        $("#modal-confirm-button").click(function() {
            $.ajax({
                type: "DELETE",
                url: '/post/delete',
                dataType: 'json',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({post_id: getParameterByName("id")}),
                success: function(data) {
                    window.location.replace('/post/manage');
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    alert("Something wrong! Cannot delete this article. Please try again.");
                }
            });
            $("#modal-confirm-dialog").modal('hide');
        });
        $("#modal-confirm-dialog").modal('toggle');
    });
});

SCRIPT;
$this->registerJs($onPostDetailJS);

?>

<input type="hidden" id="post-id" value="<?= $model->id; ?>">

<div class="row">
    <div class="col-md-2">
        <div class='panel panel-default'>
            <div class="panel-heading">
                <h3 class="panel-title" style="width: 100%; margin: 0 auto; text-align: center;">
                    <i class="glyphicon glyphicon-user"></i> &nbsp;Author
                </h3>
            </div>
            <div class='panel-body'>
                <a href="/user/profile?id=<?= $model->user->id ?>"><img src="http://gravatar.com/avatar/<?= $profile->gravatar_id ?>?s=230" class="img-circle" /></a>
                <div style="text-align: center; font-size: 13pt; padding-top: 5%;"><a href="/user/profile?id=<?= $model->user->id ?>"><?= $model->user->username ?></a></div>
                <div style="text-align: center; padding-top: 5%;">
                    at <?= Html::encode(date('F jS, Y', $model->updated_at)); ?>
                </div>
            </div>
        </div>
        <div class='panel panel-default'>
            <div class="panel-heading">
                <h3 class="panel-title" style="width: 100%; margin: 0 auto; text-align: center;">
                    <i class="glyphicon glyphicon-tags"></i> &nbsp;Tags
                </h3>
            </div>
            <div class='panel-body' style="text-align: center;">
                <?php if (!empty($model->getTags()) && count($model->getTags()) > 0): ?>
                    <?php foreach ($model->getTags() as $tag): ?>
                        <a href="/post/tag?name=<?= $tag; ?>" class="label label-info"><?php echo $tag; ?></a>
                    <?php endforeach; ?>
                <?php else: ?>
                    <div style="text-align: center;">No tags</div>
                <?php endif; ?>
            </div>
        </div>
        <?php if (!Yii::$app->user->isGuest && $model->user_id == Yii::$app->user->id): ?>
            <div class='panel panel-default'>
                <div class="panel-heading">
                    <h3 class="panel-title" style="width: 100%; margin: 0 auto; text-align: center;">
                        <i class="glyphicon glyphicon-edit"></i> &nbsp;Customize
                    </h3>
                </div>
                <div class='panel-body' style="width: 80%; margin: 0 auto; text-align: center;">
                    <?php if ($model->status == Post::STATUS_DRAFT || $model->status == Post::STATUS_DELETE): ?>
                        <?= Html::button('Publish',['id' => 'post-detail-publish-button', 'class' => 'btn btn-primary', 'style' => 'width: 100%;']) ?>
                        <br/>
                        <br/>
                    <?php endif; ?>
                    <?php if ($model->status == Post::STATUS_DRAFT || $model->status == Post::STATUS_PUBLISH): ?>
                        <?= Html::button('Edit',['id' => 'post-detail-edit-button', 'class' => 'btn btn-warning', 'style' => 'width: 100%;']) ?>
                        <br/>
                        <br/>
                        <?= Html::button('Delete',['id' => 'post-detail-delete-button', 'class' => 'btn btn-danger', 'style' => 'width: 100%;']) ?>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <div class="col-md-7">
    	<div class='panel panel-default'>
    		<div class='panel-body' style="padding-left: 5%; padding-right: 5%;">
                <?php if ($model->status == Post::STATUS_DRAFT): ?>
                    <div class="label label-warning">Draft</div>
                <?php elseif ($model->status == Post::STATUS_DELETE): ?>
                    <div class="label label-danger">In Trash</div>
                <?php endif; ?>
                <?php if ($model->type == Post::TYPE_QUESTION): ?>
                    <div class="label label-warning">Need help</div>
                <?php endif; ?>
    			<h2><label style="font-weight:bold;">
    				<?php if (!empty($model)) echo $model->title; ?>
    			</label></h2>
    			<hr class="style-two">
                <br/>
				<label class="post-content-text" style="word-wrap: break-word; line-height: 30px;">
					<?php if (!empty($model)) echo $model->content; ?>
				</label>
    		</div>
    	</div>
        <?php if ($model->status == Post::STATUS_PUBLISH): ?>
            <div class='panel panel-default'>
        		<div class='panel-body' style="padding-left: 5%; padding-right: 5%;">
                    <?= $this->render('/site/comment/_edit', [
                        'comments' => $model->comments
                    ]); ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <div class="col-md-3">
        <div class='panel panel-default'>
            <div class="panel-heading">
                <h3 class="panel-title" style="width: 100%; margin: 0 auto; text-align: center;">
                    <i class="glyphicon glyphicon-folder-open"></i> &nbsp;Related <?= $model->type == Post::TYPE_ARTICLE ? 'Articles' : 'Questions'; ?>
                </h3>
            </div>
            <div class='panel-body'>
                <ul>
                    <?php foreach ($relatedPosts as $relatedPost): ?>
                         <li><a href="/post/view?id=<?= $relatedPost->id ?>"><span style="overflow: hidden; font-size: 11pt; word-wrap:break-word;"><?= $relatedPost->title ?></span></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>