B_Sourcecode/tech-in-vein/controllers/PostController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Post;
use app\models\Comment;
use app\models\PostEditForm;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\AccessControl;
use yii\helpers\Url;

/**
* All actions of Post
*/
class PostController extends Controller
{
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					['allow' => true, 'actions' => ['create', 'manage', 'publish', 'delete', 'edit', 'comment'], 'roles' => ['@']],
					['allow' => true, 'actions' => ['view', 'tag'], 'roles' => ['?', '@']],
				],
			],
			'verbs' => [
	            'class' => \yii\filters\VerbFilter::className(),
	            'actions' => [
	                'fbauthorize'  => ['post'],
	            ],
	        ]
		];
	}

	public function actionView()
	{
		if (!Yii::$app->request->getIsGet())
		{
			return $this->render('/site/error', [
				'name' => 'Invalid request action',
				'message' => 'Your request action cannot be processed!'
			]);
		}
		$postId = Yii::$app->request->getQueryParam('id');
		if (empty($postId))
		{
			return $this->render('/site/error', [
				'name' => 'Invalid request action',
				'message' => 'Your request action cannot be processed!'
			]);
		}
		$model = Post::findOne($postId);
		if (empty($model) || ($model->status != Post::STATUS_PUBLISH && $model->user->id != Yii::$app->user->id))
		{
			return $this->render('/site/error', [
				'name' => 'Information not found',
				'message' => 'Post information cannot found!',
			]);
		}
		$model->content = $this->setCodeTag($model);
		return $this->render('/site/post/view', [
			'model' => $model,
			'profile' => $model->user->profile,
			'relatedPosts' => $model->getRelatedPosts($model->user->id, $postId, $model->type),
		]);
	}

	public function actionCreate()
	{
		// create new post form
		$model = new PostEditForm(['scenario' => PostEditForm::SCENARIO_CREATE]);

		if (Yii::$app->request->isPost)
		{
			$model->attributes = Yii::$app->request->post('PostEditForm');
			if ($model->create())
			{
				$viewUrl = Url::to(['/post/view', 'id' => $model->getPostId()]);
				return $this->redirect($viewUrl);
			}
		}

		$model->type = Post::TYPE_ARTICLE; // article
		$model->status = Post::STATUS_PUBLISH; // publish post
		return $this->render('/site/post/edit', [
			'model' => $model
		]);
	}

	public function actionEdit()
	{
		$model = new PostEditForm(['scenario' => PostEditForm::SCENARIO_EDIT]);

		if (Yii::$app->request->isGet)
		{
			$postId = Yii::$app->request->getQueryParam('id');
			$post = Post::findOne($postId);
			if (isset($post) &&
				$post->user_id == Yii::$app->user->id &&
				($post->status == Post::STATUS_PUBLISH || $post->status == Post::STATUS_DRAFT))
			{
				$model->loadAttributesFromPost($post);
				return $this->render('/site/post/edit', [
					'model' => $model
				]);
			}
		}

		if (Yii::$app->request->isPut)
		{
			$model->attributes = Yii::$app->request->post('PostEditForm');
			if ($model->edit())
			{
				$viewUrl = Url::to(['/post/view', 'id' => $model->getPostId()]);
				return $this->redirect($viewUrl);
			}
			return $this->render('/site/post/edit', [
				'model' => $model
			]);
		}

		return $this->render('/site/error', [
			'name' => 'Information not found',
			'message' => 'Post information cannot found!',
		]);
	}

	public function actionManage()
	{
		$allPostsByUser = Post::getAllPostsByUser(Yii::$app->user->id);
		return $this->render('/site/post/manage', [
			'posts' => $allPostsByUser
		]);
	}

	public function actionPublish()
	{
		if (!Yii::$app->request->isAjax || !Yii::$app->request->isPut) return false;
		// use getRawBody() or file_get_contents("php://input")
		$rawData = Yii::$app->request->getRawBody();
		$requestData = (Array)json_decode($rawData);
		$postId = $requestData['post_id'];
		if (!isset($postId)) return false;
		$post = Post::findOne($postId);
		if (!isset($post) || $post->status == Post::STATUS_PUBLISH) return false;
		return $post->edit(array('status' => Post::STATUS_PUBLISH));
	}

	public function actionDelete()
	{
		if (!Yii::$app->request->isAjax || !Yii::$app->request->isDelete) return false;
		$rawData = Yii::$app->request->getRawBody();
		$requestData = (Array)json_decode($rawData);
		$postId = $requestData['post_id'];
		if (!isset($postId)) return false;
		$post = Post::findOne($postId);
		if (!isset($post) || $post->status == Post::STATUS_DELETE) return false;
		return $post->edit(array('status' => Post::STATUS_DELETE));
	}

	public function actionTag()
	{
		if (!Yii::$app->request->isGet)
		{
			return $this->render('/site/error', [
				'name' => 'Invalid request action',
				'message' => 'Your request action cannot be processed!'
			]);
		}
		$tagName = Yii::$app->request->getQueryParam('name');
		$postsByTag = Post::getPostsByTag($tagName);
		return $this->render('/site/post/tag', [
			'postsByTag' => $postsByTag
		]);
	}

	public function actionComment()
	{
		if (!Yii::$app->request->isAjax || !Yii::$app->request->isPost) return false;
		$rawData = Yii::$app->request->getRawBody();
		$requestData = (Array)json_decode($rawData);
		$postId = $requestData['post_id'];
		$comment = $requestData['comment'];
		if (!isset($postId) || !isset($comment)) return false;
		$commentData = Yii::createObject(Comment::className());
		$commentData->post_id = $postId;
		$commentData->user_id = Yii::$app->user->id;
		$commentData->content = $comment;
		if ($commentData->create())
		{
			\Yii::$app->response->format = 'json';
			return $this->commentAttributes($commentData);
		}
		return false;
	}

	// Replace origin <pre> tag for custom Prism code tag
	private function setCodeTag(Post $post)
	{
		$postContent = $post->content;
		if (!empty($postContent))
		{
			if (strpos($postContent,'<pre>') && strpos($postContent,'</pre>'))
			{
				$postContent = str_ireplace('<pre>', '<pre><code class="language-c">', $postContent);
				$postContent = str_ireplace('</pre>', '</code></pre>', $postContent);
			}
		}
		return $postContent;
	}

	private function commentAttributes(Comment $comment)
	{
		return [
			'id'  		 => $comment->id,
			'post_id'    => $comment->post_id,
			'user_id'    => $comment->user_id,
			'comment'    => $comment->content,
			'point'      => $comment->point,
			'created_at' => $comment->created_at,
			'updated_at' => $comment->updated_at
		];
	}
}

B_Sourcecode/tech-in-vein/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\ContactForm;

use app\models\Post;
use app\models\Tag;
use app\models\EmailSubscribe;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        if (!Yii::$app->request->getIsGet())
        {
            return $this->render('/site/error', [
                'name' => 'Invalid request action',
                'message' => 'Your request action cannot be processed!'
            ]);
        }

        $postType = Yii::$app->request->get('type');
        $allPosts = Post::find()->with('comments')->where([
            'status'     => Post::STATUS_PUBLISH,
            'view_scope' => Post::SCOPE_PUBLIC,
            'type'       => (isset($postType) && ($postType == Post::TYPE_ARTICLE || $postType == Post::TYPE_QUESTION)) ? (int) $postType : Post::TYPE_ARTICLE
        ])->orderBy('updated_at DESC')->all();

        return $this->render('index', [
            'posts' => $allPosts,
            'latestPosts' => Post::getLatestPost(),
            'topTags' => Tag::getTopTags()
        ]);
    }

    public function actionSearch()
    {
        if (!Yii::$app->request->isGet) return false;
        $searchText = Yii::$app->request->get('search_text');
        if (isset($searchText)) {
            return $this->render('/site/search', [
                'posts' => [],
            ]);
        }
        $searchPosts = Post::find()->with('comments')->where(
            'status = ' . Post::STATUS_PUBLISH . ' and view_scope = ' . Post::SCOPE_PUBLIC . ' and (title like "%' . $searchText . '%" or content like "%' . $searchText . '%" or tags like "%' . $searchText . '%")'
        )->orderBy('updated_at DESC')->all();

        return $this->render('/site/search', [
            'posts' => $searchPosts,
        ]);
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionSubscribe()
    {
        if (!Yii::$app->request->isAjax || !Yii::$app->request->isPost) return false;
        $rawData = Yii::$app->request->getRawBody();
		$requestData = (Array)json_decode($rawData);
		$emailAddress = $requestData['email'];
        if (!isset($emailAddress)) return false;
        if (!filter_var($emailAddress, FILTER_VALIDATE_EMAIL)) return false;
        $subscribe = Yii::createObject(EmailSubscribe::className());
        $subscribe->email = $emailAddress;
        $subscribe->active = 1;
        return $subscribe->subscribe();
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

B_Sourcecode/tech-in-vein/views/site/_menu_left.php
<?php
use yii\widgets\menu;
?>

<div class="panel panel-default">
	<div class="panel-heading">
        <h3 class="panel-title" style="width: 100%; margin: 0 auto; text-align: center;">
            <i class="glyphicon glyphicon-globe"></i> &nbsp;Community
        </h3>
    </div>
	<div class="panel-body">
		<?php
			echo Menu::widget([
			    'items' => [
			        ['label' => 'All News', 'url' => ['site/index']],
			        ['label' => 'Articles', 'url' => ['#']],
			        ['label' => 'Questions', 'url' => ['#']],
			    ],
			    'options' => ['class' => 'nav nav-pills nav-stacked']
			]);
		?>
	</div>
</div>

<?php if(!Yii::$app->user->isGuest): ?>
<div class="panel panel-default">
	<div class="panel-heading">
        <h3 class="panel-title" style="width: 100%; margin: 0 auto; text-align: center;">
            <i class="glyphicon glyphicon-user"></i> &nbsp;Favourites
        </h3>
    </div>
	<div class="panel-body">
		<?php
			echo Menu::widget([
			    'items' => [
			        ['label' => 'My Owns', 'url' => ['site/index']],
			        ['label' => 'Bookmarks', 'url' => ['post/create']],
			    ],
			    'options' => ['class' => 'nav nav-pills nav-stacked']
			]);
		?>
	</div>
</div>
<?php endif; ?>

B_Sourcecode/tech-in-vein/views/site/_menu_right.php
<?php
use yii\widgets\menu;

$onEmailSubscribeJS = <<< 'SCRIPT'

$("#subscribe-submit-button").click(function() {
	var successText = document.getElementById("subscribe-success-text");
	var failedText = document.getElementById("subscribe-failed-text");
	var emailAddress = document.getElementById("subscribe-email-textbox").value;
	emailAddress = emailAddress.trim();
	if (emailAddress == "") {
		successText.setAttribute("style", "display: none;");
		failedText.setAttribute("style", "");
	} else {
		$.ajax({
			type: "POST",
			url: '/site/subscribe',
			data: JSON.stringify({email: emailAddress}),
			dataType: 'json',
			contentType: 'application/json; charset=utf-8',
			success: function(data) {
				failedText.setAttribute("style", "display: none;");
				successText.setAttribute("style", "");
				console.log("success");
			},
			error: function(xhr, errorStatus, thrown) {
				successText.setAttribute("style", "display: none;");
				failedText.setAttribute("style", "");
				console.log("failed");
			}
		});
	}
});

SCRIPT;

$this->registerJs($onEmailSubscribeJS);

?>

<div class="panel panel-default">
	<div class="panel-heading">
        <h3 class="panel-title" style="width: 100%; margin: 0 auto; text-align: center;">
            <i class="glyphicon glyphicon-envelope"></i> &nbsp;Email Subcription
        </h3>
    </div>
	<div class="panel-body">
		<div style="text-align: center;">
			<input id="subscribe-email-textbox" type="text" placeholder="Your email address..." style="width: 80%;">
			<br/>
			<p id="subscribe-failed-text" class="text-danger" style="display: none;">Email address subscription failed.</p>
			<p id="subscribe-success-text" class="text-success" style="display: none;">Email address subscription succeeded.</p>
			<br/>
			<input id="subscribe-submit-button" type="button" value="Subcribe" class="btn btn-danger" style="width: 50%;">
		</div>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
        <h3 class="panel-title" style="width: 100%; margin: 0 auto; text-align: center;">
            <i class="glyphicon glyphicon-time"></i> &nbsp;Update
        </h3>
    </div>
	<div class="panel-body">
		<ul>
			<?php foreach ($latestPosts as $latestPost): ?>
				 <li><a href="/post/view?id=<?= $latestPost->id ?>"><span style="overflow: hidden; font-size: 12pt; word-wrap:break-word;"><?= $latestPost->title ?></span></a></li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
        <h3 class="panel-title" style="width: 100%; margin: 0 auto; text-align: center;">
            <i class="glyphicon glyphicon-list-alt"></i> &nbsp;Tags
        </h3>
    </div>
	<div class="panel-body">
		<ul class="nav nav-pills">
			<?php foreach ($topTags as $tag): ?>
				<li><a href="/post/tag?name=<?= $tag->name; ?>" style="font-size: 11pt;">
					<?= ucfirst($tag->name); ?>
					<span class="badge">
						<?= $tag->count;  ?>
					</span>
				</a></li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>

B_Sourcecode/tech-in-vein/views/site/about.php
<?php
use yii\helpers\Url;
?>
<!-- Header banner -->
    <div class="container">
        <div class="jumbotron">
            <h1>Tech In Vein</h1>
            <p>Notebook for developers!</p>
            <a href="<?= Url::to('/user/login')?>" class="page-scroll btn btn-success">Start now</a>
        </div>
    </div>

<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Together we can</h2>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
                </span>
                <h4>Write to learn<h4>
                <blockquote>
                    <p class="text-muted">Write your technical articles as blog, manage them all with many useful features. Need help? Ask for answers!</p>
                </blockquote>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-laptop fa-stack-1x fa-inverse"></i>
                </span>
                <h4>Share with everyone</h4>
                <blockquote>
                    <p class="text-muted">Share your blog, help everyone to build their skills and also get some feedbacks, maybe a better solution.</p>
                </blockquote>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
                </span>
                <h4>Build up community</h4>
                <blockquote>
                    <p class="text-muted">We will build up a whole community in technology which brings to you a huge resource shelter in many fields.</p>
                </blockquote>
            </div>
        </div>
    </div>
</section>

B_Sourcecode/tech-in-vein/views/site/contact.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

$this->title = 'Contact';
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

    <div class="alert alert-success">
        Thank you for contacting us. We will respond to you as soon as possible.
    </div>

    <?php else: ?>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'subject') ?>
                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>
                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

    <?php endif; ?>
</div>

B_Sourcecode/tech-in-vein/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

B_Sourcecode/tech-in-vein/views/site/index.php
<?php

/* @var $this yii\web\View */
$this->title = Yii::$app->name;

?>

<div class="row">
    <div class="col-md-7 col-md-offset-1">
    	<div id="main-post-list">
    		<ul class="list-unstyled">
    			<?php foreach ($posts as $post): ?>
    				<li>
    					<?= $this->render('/site/post/_item', [
    						'post' => $post
    					]) ?>
    				</li>
    			<?php endforeach; ?>
    		</ul>
    	</div>
    </div>
    <div class="col-md-4">
        <?= $this->render('_menu_right', ['latestPosts' => $latestPosts, 'topTags' => $topTags]) ?>
    </div>
</div>

B_Sourcecode/tech-in-vein/views/site/search.php
<?php

/* @var $this yii\web\View */
$this->title = 'Search Result';
?>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
    	<div id="main-post-list">
    		<ul class="list-unstyled">
                <?php if (count($posts) > 0): ?>
        			<?php foreach ($posts as $post): ?>
        				<li>
        					<?= $this->render('/site/post/_item', [
        						'post' => $post
        					]) ?>
        				</li>
        			<?php endforeach; ?>
                <?php else: ?> 
                    <h4 class="well" style="width: 100%; margin: 0 auto; text-align: center;">
                        No results found.
                    </h4>
                <?php endif; ?>
    		</ul>
    	</div>
    </div>
</div>